# Generated by Django 4.2.2 on 2023-06-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petSociety', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipoUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipoUsuario', models.CharField(max_length=100)),
            ],
        ),
    ]
