# Generated by Django 4.2.2 on 2023-06-25 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petSociety', '0003_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_tipoUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='petSociety.tipousuario'),
            preserve_default=False,
        ),
    ]
