# Generated by Django 4.2.2 on 2023-06-25 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petSociety', '0008_usuario_id_tipousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_tipoUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='petSociety.tipousuario'),
        ),
    ]
