# Generated by Django 4.2.2 on 2023-06-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petSociety', '0010_remove_usuario_id_tipousuario_delete_tipousuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('correo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
