# Generated by Django 4.2.2 on 2023-06-25 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petSociety', '0011_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
