# Generated by Django 4.2.2 on 2023-06-25 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petSociety', '0013_tipousuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
