# Generated by Django 4.2.2 on 2023-06-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petSociety', '0014_delete_tipousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=100)),
            ],
        ),
    ]
